= National Species List Model

This repository contains a https://www.w3.org/OWL/[Web Ontology Language (OWL)] data model of the contents of the National Species List database which is used to export its information in https://www.w3.org/wiki/LinkedData[Linked Data] form.

This model is documented online at:

* https://kurrawong.github.io/nsl-model/spec.html


== License & Rights

This respository's content is licensed for reusing using the https://creativecommons.org/licenses/by/4.0/[Creative Commons BY 4.0] license, a copy of the deed of which is in the LICENSE file.

Some the content of this model is taken from other models from international standards, all of which are openly licensed.

For all the novel parts of this work:

&copy; Commonwealth of Australia (Department of Climate Change, Energy, the Environment and Water) 2023

== Contacts

Model owner:

*Endymion Cooper* +
_Biodiversity Knowledge & Innovation Manager_ +
Parks Australia +
Department of Climate Change, Energy, the Environment and Water +
endymion.cooper@environment.gov.au

Technical model designer:

*KurrawongAI* +
_Specialist IT company_ +
https://kurrawong.ai +
info@kurrawong.ai