== Introduction

The Australian National Species List (auNSL) is a taxonomic resource that provides authoritative data for names and published taxon concepts for native and naturalised taxa in Australia. See https://biodiversity.org.au/nsl/ for further information.

This data model represents the <<Semantic Web, Semantic Web>> expression of the structure of the content of the auNSL, which means its interpretation in <<OWL, OWL>> <<Class, Classes>> and <<Predicate, Predicates>> and its delivery online in <<RDF, RDF>>. With the model in this form, the content of the auNSL can then be delivered as a <<KnowledgeGraph, Knwoledge Graph>> and accessed via <<LinkedData, Linked Data>> and via services such as <<SPARQL, SPARQL>>.

=== Model Overview

This model includes a `Taxon` class which represents "A group of organisms considered by taxonomists to form a homogeneous unit" and links to that a `Taxon Name` class which represents "A name applied to Taxa by people at a point in time". Instances of `Taxon Name` are then modelled to have been used over time through a `Taxon Name Usage` class which may cite `Bibliographic Reference` class instances that indicate `Creative Work` instances which represent the papers/articles/books etc. that provide the taxon name and sometimes describe the taxon. `Taxon Name Usage` class instances may also be cited and instances of this are recorded as `Cited Usage` class instances.

An informal overview of this model is given in <<fig-overview, Figure 3>> below.

[#fig-overview,link=../img/overview.svg]
.An informal overview of the auNSL OWL Data Model showing major <<Class, Classes>> and <<Predicate, Predicates>> with the Classes defined by this model in green and those inherited from elsewhere in white. See <<fig-owl>> for a formal diagram of this model.
image::../img/overview.svg[auNSL Semantic Web Model overview,align="center"]

=== Model Context

This model exists within both a national and international domain context - other models within the general area of biodiversity, species and bibliographic referencing - and a technical context of expressing and publishing Semantic Web models.

==== Related Domain Models

The auNLS is a stand-alone system, meaning it is not dependent on any other data sources for its interpretation or use, however its content is used by many other systems such as databases of biodiversity observations, in particular the:

* https://linked.data.gov.au/dataset/bdr[Biodiversity Data Repository (BDR)]
* https://ala.org.au[Atlas of Living Australia (ALA)]

These two systems have their own models which necessarily relate to this model.

[[mapping-abis]]
===== ABIS

The BDR dataset uses the <<ABIS, ABIS>> model which contains uses the same `Taxon` and `Taxon Name` classes as defined in this model as well as the `Bibliographic Reference` and `Creative Work` classes and `cites` & `references` predicates this model also reuses for general-purpose modelling. The use of the `Taxon` and `Taxon Name` classes by ABIS is shown in the following figure.

[#fig-abis,link=../img/abis.svg]
.Classes from the <<SOSA, SOSA>> ontology used by <<ABIS, ABIS>>, shown in blue, and how they relate to classes defined by this model, shown in green. ABIS _observes_ samples (animals, plants, parts of plants, soil etc.) and declares that a `Sample` belongs to ("is a") `Taxon` or has a particular `Taxon Name` assigned to it.
image::../img/abis.svg[auNSL / ABIS relations,align="center",width=450]

This information is repeated in the <<Mappings, Mapping Section>> of this document.

===== ALA

The Atlas of Living Australia data model is, or is becoming, the new https://www.gbif.org/new-data-model[GBIF New Data Model] which declares a `Taxon` class which is the same as this model's `Taxon` class and which declares an `Identification` class which is similar to this model's `Taxon Name` class.

A Semantic Web form of the GBIF New Data Model is expected in 2024 and this auNSL/GBIF NDM relation will be updated then. For now, the mapping from this model to the GBIF NDM is given in the <<Mappings, Mappings Section>>.

==== Semantic Web

The _Semantic Web_ is the concept of a machine-readable, and perhaps more ambitiously, a machine-_understandable_ Internet.

While the original coining of the phrase in 2001 described "an expected evolution of the existing Web to a Semantic Web" and by 2006 well-known Internet pioneers lamented it as being unrealised https://en.wikipedia.org/wiki/Semantic_Web[ref], in the 2020s, there are vast amounts of data on the Internet encoded in the form expected, in 2001, to be machine-_understandable_: <<RDF, RDF>>.

In addition to RDF data on the Internet, there are many other machine-_understandable_ data encodings and originally the NSL was, and still is, encoded in another one, https://graphql.org/[GraphQL]. What those other forms of data encoding lack is the very granular, universal, identification of data elements and relationships that RDF has which make the meaning of all data elements in RDF explicit, leaving nothing ambiguous.

By choosing the express the NSL's data model in RDF, a commitment is being made to expressing all the elements of the model in a form that can be understood without implicit knowledge of the NSL or anything else, since all RDF objects and their definitions are _dereferencable_ - their definitions and details may be obtained from the Internet.

The Semantic Web, in the 2020s, relies on a few simple data models, such as <<RDF, RDF>> & <<RDFS, RDFS>> for its basic data structures and on <<OWL, OWL, the Web Ontology Language>> for its modelling paradigm. In addition to these fundamental _technical_ models, there are a series of well-known and often standardised generic domain models that are widely used by many datasets claiming to be part of the Semantic Web. For example, <<PROV, the Provenance Ontology>> is "...about entities, activities, and people involved in producing a piece of data or thing..." and is the Semantic Web's go-to model for process flow modelling. <<GSP, GeoSPARQL>> is the Semantic Web's most widely use spatial data model and <<SDO, schema.org>>.

There is value in reusing well-known models is for human understanding - it's much easier to understand a new model if it is linked to things you already know - but also in model quality - many well-known modes are well-known because they are good and widely used.

Here, expressing the NSL's data model as a Semantic Web model means not only modelling its concepts in OWL using RDF but also reusing, or at least deriving from and aligning to, these well-known models.

While is no definitive set of these well-known models and the set will surely change over time (in the 202s, schema.org is increasingly being used in favour of the earlier and smaller <<DCTERMS, Dublin Core Terms>>), this model has derived from and extended are currently in wide use and some have been for a decade or are well-known within the taxonomy domain.

The next sections describes well-known model ruse by this model in formal terms and the <<Mappings, Mappings>> section describes this model's mappings to a number of Semantic Web and similar models that aren't directly.

==== Supermodel

A 'Supermodel' is an overarching or enterprise model. The implementation of a focus model within a Supermodel context formally sets the broader context for the model by identifying and typing the other models that the focus model relates to and by defining the relations also.

The general picture of a Supermodel is that it contains:

* **Background Models**
**  reference models - usually well-known Semantic Web models - that foreground models profile
* **Vocabularies**
** controlled lists of terms that foreground models use
* **Component Models**
** individual foregound models within the Supermodel that are likely not defined elsewhere
* **Backbone Model**
** a model that sets the minimum properties of model elements across component models for integration

==== Profiling

=== Modelling Methods

==== Conceptual

Modelling Paradigm

==== Logical

Model formalisms

==== Physical

Model technology
